services:
  text_decoder_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./lightning_logs:/models  
    environment:
      - CHECKPOINT_PATH=/models/version_1/model.pt
