services:
  text_decoder_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7432:8000"
    volumes:
      - ./lightning_logs:/models
    environment:
      - CHECKPOINT_PATH=/models/version_8/model.pt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
